version: "3.9"
services:
  main:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:root@db/PythonProj

  db:
    image: postgres:14.5
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: PythonProj
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata: